name: .NET Auto-Grading

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest # Cambia a windows-latest para usar la terminal de comandos de Windows

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
      
    - name: Find Solution File
      id: find-solution
      run: |
        find . -name "*.sln" -type f -exec echo "::set-output name=solution::{}" \;
      shell: bash
      
    - name: Restore dependencies
      run: dotnet restore ${{ steps.find-solution.outputs.solution }}

    - name: Build
      run: dotnet build ${{ steps.find-solution.outputs.solution }} --no-restore
      
    - name: Test
      run: dotnet test ${{ steps.find-solution.outputs.solution }} --no-build --verbosity normal

