name: .NET Auto-Grading

on:
  workflow_dispatch:
    inputs:
      solution_file:
        description: 'test solution(.sln)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}/${{ github.event.inputs.solution_file }}

    - name: Build
      run: dotnet build ${{ github.workspace }}/${{ github.event.inputs.solution_file }} --no-restore
      
    - name: Test
      run: dotnet test ${{ github.workspace }}/${{ github.event.inputs.solution_file }} --no-build --verbosity normal
